### ISSUE TITLE
error  when  build  firmware

### ISSUE THREAD

**Issue by leksmax** [Amlogic-Lineage/android_manifest#1]
when  i  build  firmware  for  vim3  i  have  error
vendor/amlogic/common/apps/DroidTvSettings/src/com/droidlogic/tv/settings/display/outputmode/OutputUiManager.java:464: error: cannot find symbol
            strVesaEdid = mOutputModeManager.getHdmiVesaSupportList();
how repair  this  error

**Comment by assegaf** [comment]
probably now fixed, cause I have compiled no error of those.
